//
// Academic License - for use in teaching, academic research, and meeting
// course requirements at degree granting institutions only.  Not for
// government, commercial, or other organizational use.
//
// go1_FR_leg_inverse_dynamics_thigh_zero.cpp
//
// Code generation for function 'go1_FR_leg_inverse_dynamics_thigh_zero'
//

// Include files
#include "go1_FR_leg_inverse_dynamics_thigh_zero.h"

#include <cmath>

// Function Definitions
void go1_FR_leg_inverse_dynamics_thigh_zero() {
    taulist.setZero();
    double b_t170_tmp;
    double b_t171_tmp;
    double c_t170_tmp;
    double c_t171_tmp;
    double d_t170_tmp;
    double t10;
    double t100;
    double t102;
    double t103;
    double t103_tmp;
    double t106;
    double t11;
    double t110;
    double t110_tmp;
    double t12;
    double t126;
    double t127;
    double t128;
    double t130;
    double t132;
    double t133;
    double t135;
    double t14;
    double t149;
    double t151;
    double t154;
    double t159;
    double t16;
    double t160;
    double t162;
    double t163;
    double t164;
    double t165;
    double t166;
    double t167;
    double t169;
    double t170;
    double t170_tmp;
    double t171_tmp;
    double t18;
    double t19;
    double t23;
    double t4;
    double t42;
    double t43;
    double t44;
    double t45;
    double t47;
    double t5;
    double t51;
    double t51_tmp;
    double t53;
    double t53_tmp;
    double t57;
    double t6;
    double t64;
    double t65;
    double t71;
    double t71_tmp;
    double t72_tmp;
    double t8;
    double t81;
    double t81_tmp;
    double t83;
    double t84;
    double t90;
    double t93;
    double t98;
    double t99;
    double t99_tmp;
    // go1_FR_leg_inverse_dynamics_thigh_zero
    //     TAULIST = go1_FR_leg_inverse_dynamics_thigh_zero(IN1,IN2,IN3)
    //     This function was generated by the Symbolic Math Toolbox version 9.2.
    //     29-Jun-2023 13:47:20
    t4 = std::abs(q[0]);
    t5 = std::abs(q[2]);
    t6 = dq[1] + dq[2];
    t11 = dq[0] * dq[0];
    t12 = dq[1] * dq[1];
    t14 = q[2] * q[2];
    t42 = dq[1] * 2.55679E-7;
    t43 = dq[2] * 2.55679E-7;
    t44 = dq[1] * 2.077264E-6;
    t45 = dq[2] * 2.077264E-6;
    t47 = dq[0] * 0.033451;
    t90 = dq[0] * 0.0045447197620000013;
    t8 = std::cos(t5);
    t10 = std::sin(t5);
    t16 = 1.0 / t4;
    t18 = 1.0 / t5;
    t99_tmp = dq[0] * dq[1];
    t99 = ddq[1] * 0.033451 + t99_tmp * -0.063146;
    t19 = t18 * t18;
    t51_tmp = dq[0] * q[2] * t10 * t18;
    t51 = t51_tmp * 0.116695;
    t53_tmp = dq[1] * q[2] * t10 * t18;
    t53 = t53_tmp * 0.033451;
    t57 = t51_tmp * 0.016646;
    t65 = t51_tmp * t43;
    t93 = t51_tmp * 0.002261558852;
    t98 = -(dq[1] * 0.003342) + dq[0] * 0.063146;
    t23 = t14 * t19 * (t8 - 1.0);
    t103_tmp = q[2] * t10 * t18;
    t103 = t103_tmp * t98;
    t64 = t23 * 0.016646;
    t110_tmp = q[0] * q[0] * (t16 * t16) * (std::cos(t4) - 1.0);
    t110 = ((t110_tmp * 9.81 + ddq[1] * 0.003342) - ddq[0] * 0.063146) + 9.81;
    t71_tmp = dq[1] * (t23 + 1.0);
    t71 = t71_tmp * 0.033451;
    t72_tmp = dq[0] * (t23 + 1.0);
    t83 = t72_tmp * t44;
    t84 = t72_tmp * t45;
    t100 = t23 * 0.016646 + 0.016646;
    t106 = (t23 + 1.0) * t98;
    t81_tmp = ddq[0] * (t23 + 1.0);
    t81 = -(t81_tmp * 2.55679E-7);
    t102 = dq[0] * (t64 + 0.016646);
    t128 = ((t44 + t45) + t51_tmp * 2.4787446E-5) + t72_tmp * 7.117814E-6;
    t126 = ((dq[1] * 0.001100428748 + dq[2] * 0.001100428748) +
            t51_tmp * 2.077264E-6) -
           t72_tmp * 2.55679E-7;
    t127 = ((t42 + t43) - t51_tmp * 7.117814E-6) - t72_tmp * 0.001088793059;
    t45 = t14 * t18 * (t8 - 1.0);
    t44 = q[2] * (t5 + -t14 * t19 * (t5 - t10));
    t133 = ((-(t103_tmp * 0.009539) + t23 * 0.296244) +
            -t18 * (t45 * 0.116695 - t44 * 0.0061970000000000011)) +
           0.296244;
    t132 = -(t72_tmp * t128);
    t43 = dq[1] * t133;
    t130 = -(t51_tmp * t127);
    t135 = ((t103_tmp * 0.296244 + t23 * 0.009539) -
            t18 * (t45 * 0.0061970000000000011 + t44 * 0.116695)) +
           0.009539;
    t149 = (((dq[2] * 0.116695 - t57) + t71) - t103) + t43;
    t45 = dq[1] * t135;
    t162 = (((dq[2] * 0.01585441609 - t93) + t71_tmp * 0.0045447197620000013) -
            t103 * 0.135862) +
           t43 * 0.135862;
    t151 = t103_tmp * t135 + (t23 + 1.0) * t133;
    t154 = (((dq[2] * 0.0061970000000000011 + t53) + t102) + t106) + t45;
    t163 = t6 * t162;
    t44 = dq[0] * t151;
    t165 = (((dq[2] * 0.00084193681400000016 + t53_tmp * 0.0045447197620000013) +
             t102 * 0.135862) +
            t106 * 0.135862) +
           t45 * 0.135862;
    t167 = t154 * t162;
    t159 = t47 + t44;
    t166 = t6 * t165;
    t160 = t90 + t44 * 0.135862;
    t169 = -(t149 * t165);
    t164 = t72_tmp * t160;
    t170_tmp = ddq[1] * t135;
    b_t170_tmp = dq[2] * ((((dq[1] * 0.116695 + t57) - t71) + t103) - t43);
    c_t170_tmp = (t23 + 1.0) * t110;
    d_t170_tmp = t103_tmp * t99;
    t170 = (((((((-(ddq[2] * 0.00084193681400000016) + dq[1] * t93) -
                 ddq[0] * (t64 + 0.016646) * 0.135862) -
                d_t170_tmp * 0.135862) +
               c_t170_tmp * 0.135862) -
              t170_tmp * 0.135862) +
             b_t170_tmp * 0.135862) +
            t163) +
           t164;
    t171_tmp = ddq[0] * q[2] * t10 * t18;
    b_t171_tmp = ddq[1] * t133;
    c_t171_tmp = dq[1] * t102;
    t106 = dq[2] *
           ((((-(dq[1] * 0.0061970000000000011) + t53) + t102) + t106) + t45);
    t53 = (t23 + 1.0) * t99;
    t57 = t103_tmp * t110;
    t103 = (((((((ddq[2] * 0.01585441609 - t171_tmp * 0.002261558852) +
                 c_t171_tmp * -0.135862) +
                t53 * 0.135862) +
               t57 * 0.135862) +
              b_t171_tmp * 0.135862) -
             t106 * 0.135862) +
            t51_tmp * t160) +
           t166;
    t71 = dq[0] * dq[2];
    t93 = ddq[0] * t151;
    t64 = dq[2] * (t51 - t72_tmp * 0.0061970000000000011);
    t5 = q[0] * std::sin(t4) * t16;
    t14 = t103_tmp * t133 - (t23 + 1.0) * t135;
    t19 = t99_tmp * (t23 + 1.0);
    t71_tmp = t71 * (t23 + 1.0);
    t53_tmp = t99_tmp * q[2] * t10 * t18;
    t71 = t71 * q[2] * t10 * t18;
    t44 = t51_tmp * t162;
    t45 = (t23 + 1.0) * t170;
    t43 = dq[1] * 0.000572001265 - dq[0] * 0.000218457134;
    t8 = t103_tmp * t103;
    taulist[0] =
        (((((ddq[0] * 0.0096609453510266615 +
             (ddq[1] * -0.00013665441044 - t11 * 0.00194331309832)) +
            (t12 * -0.00194331309832 - t99_tmp * 0.000336495370084604)) +
           (((((t93 * 0.0045447197620000013 + dq[0] * t98 * 0.03077492) -
               t45 * 0.063146) -
              t100 * t170) -
             (t23 + 1.0) * (((((((ddq[1] * 2.55679E-7 + ddq[2] * 2.55679E-7) -
                                 t81_tmp * 0.001088793059) -
                                t6 * t128) -
                               t154 * t160) +
                              t159 * t165) -
                             t19 * 7.117814E-6) +
                            ((((t71_tmp * -7.117814E-6 - t171_tmp * 7.117814E-6) +
                               t53_tmp * 0.001088793059) +
                              t71 * 0.001088793059) +
                             t51_tmp * t126))) +
            dq[1] * t43)) +
          ((t64 * -0.0045447197620000013 +
            t151 * (((ddq[0] * 0.0045447197620000013 - t99_tmp * 0.000454050804) +
                     t93 * 0.135862) +
                    ((((t64 * -0.135862 + t72_tmp * t165) + t5 * 1.33280622) -
                      t99_tmp * t14 * 0.135862) -
                     t44))) +
           t5 * 0.34707703248522)) +
         (((((t110_tmp * -0.51916372127999988 + (t23 + 1.0) * t47 * t165) -
             dq[1] * t90 * t14) -
            t8 * 0.079791999999999988) +
           t103_tmp * (((((((ddq[1] * 2.077264E-6 + ddq[2] * 2.077264E-6) +
                            t81_tmp * 7.117814E-6) +
                           t6 * t127) -
                          t149 * t160) +
                         t159 * t162) +
                        t19 * 2.4787446E-5) +
                       ((((t71_tmp * 2.4787446E-5 + t72_tmp * t126) +
                          t171_tmp * 2.4787446E-5) -
                         t53_tmp * 7.117814E-6) -
                        t71 * 7.117814E-6))) -
          t44 * 0.033451)) -
        0.51916372127999988;
    taulist[1] =
        (((((ddq[0] * -0.00013665441044 + ddq[1] * 0.0066258277698) +
            ddq[2] * 0.001100428748) +
           (((((((((t11 * 0.00010284978264 + t12 * 0.00010284978264) + t65) +
                  t81) +
                 t83) +
                t84) +
               t130) +
              t132) +
             t167) +
            t169)) +
          ((((t99_tmp * -0.00137131183332 + dq[1] * t98 * 0.03077492) +
             t45 * 0.003342) +
            (t23 + 1.0) * t103 * 0.033451) +
           t133 * t103)) +
         ((((((-t135 * t170 - dq[0] * t43) + t110_tmp * 0.0301622184) +
             t171_tmp * 2.077264E-6) -
            t103_tmp * t170 * 0.033451) +
           t8 * 0.003342) +
          t51_tmp * t42)) +
        0.0301622184;
    taulist[2] =
        ((((((((((((((ddq[1] * 0.001100428748 + ddq[2] * 0.0029557773160589071) +
                     t65) +
                    t81) +
                   t83) +
                  t84) +
                 t130) +
                t132) -
               t163 * 0.0061970000000000011) +
              ((((t164 * -0.0061970000000000011 + t166 * 0.116695) + t167) +
                t169) +
               ddq[0] * t100 * 0.00084193681400000016)) +
             (b_t171_tmp * 0.01585441609 + t170_tmp * 0.00084193681400000016)) +
            (c_t171_tmp * -0.01585441609 - b_t170_tmp * 0.00084193681400000016)) +
           (t106 * -0.01585441609 + t53 * 0.01585441609)) +
          ((c_t170_tmp * -0.00084193681400000016 + t51 * t160) -
           t171_tmp * 0.00026183534623414)) +
         (d_t170_tmp * 0.00084193681400000016 + t57 * 0.01585441609)) +
        t53_tmp * -1.3759201205844E-5;
}

// End of code generation (go1_FR_leg_inverse_dynamics_thigh_zero.cpp)
