function dtheta_sym = cal_go1_FR_dq(in1,in2)
%cal_go1_FR_dq
%    DTHETA_SYM = cal_go1_FR_dq(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    01-Jul-2023 17:50:40

t1 = in1(1,:);
t2 = in1(2,:);
t3 = in1(3,:);
vx = in2(1,:);
vy = in2(2,:);
vz = in2(3,:);
t5 = cos(t1);
t6 = cos(t2);
t7 = cos(t3);
t8 = sin(t1);
t9 = sin(t2);
t10 = sin(t3);
t11 = t2+t3;
t12 = t6.^2;
t13 = t7.^2;
et1 = vx.*sin(t2.*2.0).*-1.065e+5-vx.*sin(t3.*2.0).*1.065e+5-t8.*vy.*2.13e+5+t5.*vz.*2.13e+5+t10.*t12.*vx.*2.13e+5+t8.*t12.*vy.*2.13e+5+t8.*t13.*vy.*2.13e+5-t5.*t12.*vz.*2.13e+5-t5.*t13.*vz.*2.13e+5+t6.*t7.*t9.*vx.*2.13e+5+t6.*t9.*t13.*vx.*4.26e+5+t7.*t10.*t12.*vx.*4.26e+5+t5.*t6.*t7.*vy.*8.12e+4-t5.*t9.*t10.*vy.*8.12e+4-t7.*t8.*t12.*vy.*2.13e+5-t8.*t12.*t13.*vy.*4.26e+5+t6.*t7.*t8.*vz.*8.12e+4+t5.*t7.*t12.*vz.*2.13e+5;
et2 = t8.*t9.*t10.*vz.*-8.12e+4+t5.*t12.*t13.*vz.*4.26e+5+t6.*t8.*t9.*t10.*vy.*2.13e+5-t5.*t6.*t9.*t10.*vz.*2.13e+5+t6.*t7.*t8.*t9.*t10.*vy.*4.26e+5-t5.*t6.*t7.*t9.*t10.*vz.*4.26e+5;
dtheta_sym = [(t5.*vy.*1.0e+3+t8.*vz.*1.0e+3)./(t6.*2.13e+2+cos(t11).*2.13e+2);(et1+et2)./((t9-sin(t11)).*(t7+1.0).*4.5369e+4);(t9.*vx.*2.13e+5+t5.*vy.*8.12e+4+t8.*vz.*8.12e+4+t6.*t10.*vx.*2.13e+5+t7.*t9.*vx.*2.13e+5-t6.*t8.*vy.*2.13e+5+t5.*t6.*vz.*2.13e+5-t6.*t7.*t8.*vy.*2.13e+5+t8.*t9.*t10.*vy.*2.13e+5+t5.*t6.*t7.*vz.*2.13e+5-t5.*t9.*t10.*vz.*2.13e+5)./(t10.*4.5369e+4)];
